import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Control from '../components/Control';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Volodya - Konva JS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <Control />
      </main>

      <footer className={styles.footer}>
        Analysed and Konva JS
      </footer>
    </div>
  )
}

export default Home
